#! /bin/sh
xsetroot -cursor_name left_ptr
bspc rule -r "*"


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 Web Dev Confs Media Steam Games 8 9

bspc config border_width         2
bspc config window_gap          12
bspc config bottom_padding 30


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### ------------------------ ###
###        Rules             ###
### ------------------------ ###
# Default Rules
bspc rule -a Screenkey manage=off
bspc rule -a Polydock manage=off

# Media
# Confs
bspc rule -a discord desktop='Confs'
bspc rule -a zoom desktop='Confs'
### Steam and Steam Games
bspc rule -a Steam desktop='Steam' follow=on
# Timberborn
bspc rule -a steam_app_1062090 desktop='Games' state=fullscreen follow=on
# Bomber Crew
bspc rule -a BomberCrew.x86_64 desktop='Games' state=fullscreen follow=on
# Paavu Audio Controller
bspc rule -a Pavucontrol state=floating
# Minecraft
bspc rule -a "Minecraft* 1.18.1" desktop='Games' follow=off
bspc rule -a MultiMC desktop='Steam'
# thunar
bspc rule -a "Thunar"
# gthumb
bspc rule -a "Gthumb" state=floating
# evnince
bspc rule -a "Evince" state=floating

# Web
bspc rule -a "Brave-browser" desktop='Web'
bspc rule -a Chromium desktop='Web'
bspc rule -a "LibreWolf" desktop='Web'

### ------------------------ ###
###        End Rules         ###
### ------------------------ ###

# Launch Polybar
killall -q polybar
$HOME/.config/polybar/launch.sh

# add spotify listener
killall -q spotify-listener
spotify-listener &
#restart-app.sh spotify-listener 

# add walpaper
feh --bg-fill ~/Pictures/Firekeeper.png &

# add compositor
killall -q picom
picom &
#restart-app.sh picom 

# add notification manager
killall -q dunst
dunst &
#restart-app.sh dunst 

killall -q nm-applet
nm-applet --indicator
#restart-app.sh nm-applet "--indicator" 

# add usb manager
killall -q udiskie
udiskie -s &
#restart-app.sh udiskie "-o rw -s" 

killall -q cairo-dock
cairo-dock &
#restart-app.sh cairo-dock 
