#! /bin/sh
xsetroot -cursor_name left_ptr
bspc rule -r "*"


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 Browsers Dev Discord Zoom Steam Games

bspc config border_width         2
bspc config window_gap          12
bspc config bottom_padding 30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### ------------------------ ###
###        Rules             ###
### ------------------------ ###
# Default Rules
bspc rule -a Screenkey manage=off
bspc rule -a Polydock manage=off

# Zoom
bspc rule -a zoom desktop='Zoom' state=floating
# Discord
bspc rule -a discord desktop='Discord'
### Steam and Steam Games
bspc rule -a Steam desktop='Steam' follow=on
# Timberborn
bspc rule -a steam_app_1062090 desktop='Games' state=fullscreen follow=on
# Bomber Crew
bspc rule -a BomberCrew.x86_64 desktop='Games' state=fullscreen follow=on
# Paavu Audio Controller
bspc rule -a Pavucontrol state=floating
# thunar
bspc rule -a "Thunar" state=floating
# gthumb
bspc rule -a "Gthumb" state=floating
# evnince
bspc rule -a "Evince" state=floating

# terminal
bspc rule -a "Alacritty" desktop='Dev' follow=on

# Browsers
bspc rule -a "Brave-browser" desktop='Browsers'
bspc rule -a Chromium desktop='Browsers'
bspc rule -a "LibreWolf" desktop='Browsers'

### ------------------------ ###
###        End Rules         ###
### ------------------------ ###

# Launch Polybar
killall -q polybar
$HOME/.config/polybar/launch.sh

# add spotify listener
killall -q spotify-listener
spotify-listener &

# add walpaper
feh --bg-fill ~/Pictures/FirekeeperFull.jpg

# add compositor
killall -q picom
picom &

# add notification manager
killall -q dunst
dunst &

killall -q polydock
polydock &

killall nm-applet
nm-applet --indicator
